#pragma once
#include "symbolic.hpp"
#include <vector>
#include <string>
#include <map>

namespace lamina {

class LAMINA_API Solver {
public:
    
    
    
    
    
    static std::map<std::string, SymbolicExpr> solve_linear_system(
        const std::vector<SymbolicExpr>& equations, 
        const std::vector<std::string>& variables);

    
    
    static std::vector<SymbolicExpr> groebner_basis(
        const std::vector<SymbolicExpr>& polynomials,
        const std::vector<std::string>& variables);

    
    
    
    
    static std::vector<std::map<std::string, SymbolicExpr>> solve_polynomial_system(
        const std::vector<SymbolicExpr>& equations,
        const std::vector<std::string>& variables);

    // Compute a reduced Gröbner basis (minimal + inter-reduced + monic)
    static std::vector<SymbolicExpr> reduced_groebner_basis(
        const std::vector<SymbolicExpr>& polynomials,
        const std::vector<std::string>& variables);

    // Test if a polynomial belongs to the ideal generated by the given basis
    // Precondition: 'basis' should be a Gröbner basis (call groebner_basis first)
    static bool ideal_membership(
        const SymbolicExpr& polynomial,
        const std::vector<SymbolicExpr>& basis,
        const std::vector<std::string>& variables);

    // Compute the elimination ideal: elements of the basis that only involve
    // variables[elim_count], variables[elim_count+1], ..., variables[n-1]
    // (i.e., eliminate the first 'elim_count' variables)
    // Precondition: 'basis' should be a Gröbner basis computed with lex order
    // where the eliminated variables come first
    static std::vector<SymbolicExpr> elimination_ideal(
        const std::vector<SymbolicExpr>& basis,
        const std::vector<std::string>& variables,
        int elim_count);
};

} 
