set(LMCAS_EXACT_NUMERIC_SOURCES
    src/bigint.cpp
    src/bigint_arithmetic.cpp
    src/bigint_combinatorics.cpp
    src/bigint_number_theory.cpp
    src/rational.cpp
    src/rational_parsing.cpp
    src/rational_representation.cpp
    src/rational_roots.cpp
    src/irrational.cpp
    src/irrational_arithmetic.cpp
    src/irrational_representation.cpp
    src/exact_constant_bounds.cpp
    src/unit.cpp
    src/lmmc_lifecycle.cpp
    src/exact_sturm.cpp
    src/exact_algebraic.cpp
    src/exact_algebraic_refinement.cpp
    src/exact_root.cpp
    src/complex_root_isolation.cpp
    src/complex_root_projection.cpp
    src/complex_root_winding.cpp
    src/complex_root_rectangles.cpp
    src/rational_polynomial.cpp
    src/rational_square_free.cpp
    src/univariate_factor_bridge.cpp
    src/berlekamp.cpp
    src/berlekamp_basis.cpp
    src/berlekamp_modular.cpp
    src/berlekamp_split.cpp
    src/hensel_lift.cpp
    src/zassenhaus_combine.cpp
    src/exact_rational_determinant.cpp
    src/exact_rational_solve.cpp
)

set(LMCAS_CORE_SOURCES
    src/expression_analysis.cpp
    src/rewrite_budget.cpp
    src/quantity.cpp
    src/symbolic_set.cpp
    src/symbolic_core.cpp
    src/normalization_arithmetic.cpp
    src/normalization_functions.cpp
    src/normalization_structural.cpp
    src/facts_query.cpp
    src/facts_query_adapters.cpp
    src/expand_visitor.cpp
    src/numeric_evaluation.cpp
    src/print_visitor.cpp
    src/matcher.cpp
    src/irrational_symbolic.cpp
    src/poly_utils.cpp
    src/rational_polynomial_recognition.cpp
    src/root_of_identity.cpp
    src/interval.cpp
    src/interval_endpoint.cpp
    src/interval_endpoint_order.cpp
    src/interval_normalization.cpp
    src/interval_set_operations.cpp
    src/interval_serialization.cpp
    src/symbolic_construction.cpp
    src/symbolic_factory.cpp
    src/symbolic_node_order.cpp
    src/symbolic_number_order.cpp
    src/differentiation_arithmetic.cpp
    src/differentiation_functions.cpp
    src/differentiation_structural.cpp
    src/squared_norm.cpp
    src/numeric_evaluation_nodes.cpp
    src/numeric_evaluation_functions.cpp
    src/numeric_evaluation_power.cpp
    src/rewrite_engine.cpp
    src/normalization_products.cpp
    src/normalization_matrices.cpp
    src/normalization_powers.cpp
    src/normalization_numeric_powers.cpp
    src/normalization_numeric_functions.cpp
    src/normalization_trigonometric.cpp
    src/normalization_norms.cpp
    src/normalization_signs.cpp
    src/normalization_utils.cpp
)

set(LMCAS_ASSUMPTION_SOURCES
    src/property_store.cpp
    src/relation_store.cpp
    src/inference_engine_core.cpp
    src/inference_engine_arithmetic.cpp
    src/inference_engine_bounds.cpp
    src/inference_engine_monotonicity.cpp
    src/assumption_context.cpp
    src/assumption_simplification.cpp
    src/query_interface.cpp
    src/assumption_queries.cpp
    src/assumption_conditionals.cpp
    src/assumption_serialization.cpp
    src/property_store_support.cpp
    src/property_classification.cpp
    src/property_intervals.cpp
    src/query_special_values.cpp
    src/query_conditions.cpp
    src/inference_engine_sign_queries.cpp
    src/inference_engine_facts.cpp
    src/inference_engine_domains.cpp
    src/inference_engine_relations.cpp
    src/inference_engine_product.cpp
    src/inference_engine_power.cpp
    src/inference_engine_functions.cpp
    src/inference_engine_periodicity.cpp
)

set(LMCAS_MATRIX_KERNEL_SOURCES
    src/exact_matrix.cpp
    src/exact_matrix_support.cpp
    src/exact_matrix_determinant.cpp
    src/exact_matrix_solve.cpp
)

set(LMCAS_ALGEBRA_SOURCES
    src/complex_quadratic.cpp
    src/residual_verification.cpp
    src/residual_comparison.cpp
    src/equivalence_options.cpp
    src/equivalence_proof.cpp
    src/equivalence_trig.cpp
    src/equivalence_exp_log.cpp
    src/equivalence_complex.cpp
    src/equivalence_engine.cpp
    src/symbolic_gcd.cpp
    src/symbolic_algebra_adapter.cpp
    src/symbolic_factor.cpp
    src/multivariate_factor.cpp
    src/multivariate_factor_checked.cpp
    src/multivariate_factor_evaluation.cpp
    src/multivariate_factor_patterns.cpp
    src/multivariate_hensel.cpp
    src/multivariate_poly.cpp
    src/solver_linear.cpp
    src/solver_groebner.cpp
    src/solver_assumptions.cpp
    src/solve_polynomial.cpp
    src/solve_polynomial_normalization.cpp
    src/solve_polynomial_quadratic.cpp
    src/solve_polynomial_cubic.cpp
    src/solve_polynomial_cubic_numeric.cpp
    src/solve_polynomial_quartic.cpp
    src/solve_polynomial_quartic_symbolic.cpp
    src/solve_polynomial_resolvent.cpp
    src/solve_transcendental.cpp
    src/solve_mixed_transcendental.cpp
    src/solve_visitor.cpp
    src/solve_solution_finalization.cpp
    src/newton_raphson.cpp
    src/root_of_utils.cpp
    src/inequality_solver.cpp
    src/inequality_solver_numeric.cpp
    src/inequality_solver_polynomial.cpp
    src/parametric_solver.cpp
    src/transcendental_factor.cpp
    src/transcendental_polynomial.cpp
    src/transcendental_substitution.cpp
    src/transcendental_rewrite.cpp
    src/fglm.cpp
    src/fglm_dimension.cpp
    src/fglm_linear.cpp
    src/fglm_polynomial.cpp
    src/multivariate_poly_arithmetic.cpp
    src/multivariate_poly_evaluation.cpp
    src/solver_groebner_poly.cpp
    src/solver_groebner_builder.cpp
    src/solver_groebner_conversion.cpp
    src/solver_groebner_reconstruction.cpp
    src/solver_groebner_basis.cpp
    src/solver_groebner_system.cpp
    src/mixed_transcendental_classification.cpp
    src/mixed_transcendental_search.cpp
    src/mixed_transcendental_evaluation.cpp
    src/mixed_transcendental_isolation.cpp
    src/mixed_transcendental_refinement.cpp
    src/mixed_transcendental_deduplication.cpp
    src/mixed_transcendental_numeric.cpp
    src/transcendental_patterns.cpp
    src/transcendental_inversion.cpp
    src/transcendental_solver_substitution.cpp
    src/transcendental_pythagorean.cpp
    src/inequality_solver_ordering.cpp
    src/inequality_solver_chart.cpp
    src/inequality_solver_rational.cpp
    src/inequality_solver_parametric.cpp
    src/parametric_solver_branches.cpp
    src/solver_imaginary.cpp
    src/symbolic_cancel.cpp
)

set(LMCAS_CALCULUS_SOURCES
    src/limit_visitor_taylor.cpp
    src/limit_visitor_core.cpp
    src/limit_result.cpp
    src/symbolic_calculus_adapter.cpp
    src/integration_table.cpp
    src/integration_basic_strategies.cpp
    src/integration_trigonometric.cpp
    src/integrator.cpp
    src/integration_rational.cpp
    src/integration_special_functions.cpp
    src/multiple_integral.cpp
    src/integration_weierstrass.cpp
    src/integration_trig_substitution.cpp
    src/calculus_utils.cpp
    src/numerical_integration.cpp
    src/calculus_continuity.cpp
    src/calculus_asymptotes.cpp
    src/calculus_inverse.cpp
    src/calculus_curvature.cpp
    src/calculus_revolution.cpp
    src/limit_visitor_arithmetic.cpp
    src/limit_visitor_asymptotic.cpp
    src/limit_visitor_composition.cpp
    src/limit_visitor_direction.cpp
    src/limit_visitor_evaluation.cpp
    src/limit_visitor_predicates.cpp
    src/limit_visitor_product.cpp
    src/limit_visitor_product_special.cpp
    src/limit_visitor_squeeze.cpp
    src/integration_substitution.cpp
    src/integration_by_parts.cpp
    src/integration_partial_fraction.cpp
    src/integration_rational_collection.cpp
    src/integration_rational_factorization.cpp
    src/integration_rational_coefficients.cpp
    src/integration_rational_terms.cpp
    src/integration_table_elementary.cpp
    src/integration_table_algebraic.cpp
    src/integration_table_composite.cpp
    src/integration_preprocess.cpp
    src/integration_linearity.cpp
    src/integration_definite.cpp
    src/integration_definite_algebraic.cpp
    src/integration_definite_segments.cpp
)

set(LMCAS_LINEAR_ALGEBRA_SOURCES
    src/symbolic_matrix.cpp
    src/symbolic_matrix_support.cpp
    src/symbolic_matrix_solve.cpp
    src/symbolic_matrix_transform.cpp
    src/symbolic_matrix_eigen.cpp
    src/matrix_decomposition.cpp
    src/matrix_decomposition_support.cpp
    src/matrix_decomposition_lu.cpp
    src/matrix_decomposition_qr.cpp
    src/matrix_decomposition_cholesky.cpp
    src/matrix_decomposition_svd.cpp
    src/matrix_decomposition_eigen.cpp
)

set(LMCAS_ANALYSIS_SOURCES
    src/symbolic_ode.cpp
    src/ode_classification.cpp
    src/ode_first_order.cpp
    src/ode_linear.cpp
    src/ode_characteristic_roots.cpp
    src/ode_advanced.cpp
    src/symbolic_geometry.cpp
    src/symbolic_implicit_diff.cpp
    src/symbolic_geometry_vector.cpp
    src/symbolic_geometry_line_plane.cpp
    src/symbolic_geometry_line.cpp
    src/symbolic_geometry_plane.cpp
    src/symbolic_geometry_quadric.cpp
    src/symbolic_geometry_surface.cpp
    src/symbolic_geometry_support.cpp
    src/symbolic_quadric_classification.cpp
    src/symbolic_complex.cpp
    src/vector_calculus_support.cpp
    src/vector_calculus_differential.cpp
    src/vector_calculus_integrals.cpp
    src/vector_calculus_integral_api.cpp
    src/vector_calculus_extrema.cpp
    src/vector_calculus_algebra.cpp
    src/series_engine.cpp
    src/series_convergence.cpp
    src/series_expansions.cpp
    src/transform_laplace.cpp
    src/transform_inverse_laplace.cpp
    src/transform_fourier.cpp
    src/transform_z.cpp
    src/transform_convolution.cpp
    src/transform_support.cpp
    src/complex_analysis.cpp
    src/differential_geometry.cpp
    src/matrix_quadratic_form.cpp
    src/vector_calculus_curves.cpp
    src/vector_calculus_surfaces.cpp
    src/vector_calculus_directional.cpp
    src/vector_calculus_matrices.cpp
    src/vector_calculus_lagrange.cpp
    src/ode_frobenius.cpp
    src/ode_support.cpp
    src/series_sequence_limits.cpp
)

set(LMCAS_FACADE_SOURCES
    src/assumption_deserialization.cpp
    src/assumption_parse_properties.cpp
    src/assumption_parse_intervals.cpp
    src/assumption_parse_relations.cpp
    src/assumption_parse_atoms.cpp
    src/assumption_parse_values.cpp
    src/expr_complex_evaluation.cpp
    src/expr_equivalence.cpp
    src/expr_errors.cpp
    src/expr_parsing.cpp
    src/expr_sets.cpp
    src/expr_solving.cpp
    src/expr_facade.cpp
    src/expr_arithmetic.cpp
    src/expr_transform.cpp
    src/expr_values.cpp
    src/value_facade.cpp
    src/value.cpp
    src/expr_elementary.cpp
    src/expr_parser_construction.cpp
    src/expr_parser_functions.cpp
    src/expr_number_domains.cpp
)
